# Advanced Placement Statistics syllabus
*** If you are a teacher or interested in the design of the course, see the [meta](https://github.com/APStats/syllabus/blob/master/meta.md) document.***

* **Course:** [AP Statistics - 25117X0HC0](http://wsfcs.k12.nc.us/Domain/131)
* **Instructor:** Kay Endriss, [ekendriss@wsfcs.k12.nc.us](mailto:ekendriss@wsfcs.k12.nc.us)
* **Need help?**
    * Look through and create [issues](https://github.com/APStats/syllabus/issues)
    * Office Hours: before school or after school, by appointment. Please contact me to make arrangements that are mutually agreeable.
      * [Canvas Inbox Message](https://canvas.instructure.com/conversations#filter=type=inbox)
      * [Email](mailto:ekendriss@wsfcs.k12.nc.us)

## Course Description ##

The purpose of the AP course in statistics is to introduce students to the major concepts and tools for collecting, analyzing and drawing conclusions from data. Students are exposed to four broad conceptual themes:
 1. Exploring Data: Describing patterns and departures from patterns
 2. Sampling and Experimentation: Planning and conducting a study
 3. Anticipating Patterns: Exploring random phenomena using probability and simulation
 4. Statistical Inference: Estimating population parameters and testing hypotheses

[Career Center](http://wsfcs.k12.nc.us/Domain/104) offers AP Statistics as a year-long course, which is equivalent to a one-semester, introductory, non-calculus based, college course in statistics.

## Prerequisites and Necessary Skills ##

* Completed or enrolled in Precalculus. This helps insure students have the mathematical maturity necessary for success in this course.
* Working knowledge of algebra (reunion of broken parts) sufficient to use it as a tool when solving problems.
* Working knowledge of geometry sufficient for finding areas of basic geometric shapes.
* Reading comprehension skills sufficient to read and understand problems from a wide variety of disciplines. Statistics is used to make sense of data in almost all fields.
* Ability and willingness to communicate technical information in writing and thus help educate others. Statistics is a consEven budding statisticians must be able to communicate what assumpitions they have made, what analyses they have done, and what it all means to their clients. 


## Tools for Calculating and Computing ##

* Students will need access to a [graphing calculator](https://github.com/APStats/syllabus/calculator) during the course and for the advanced placement exam. 
* Career Center enjoys a sitewide JMP license, which students may use to complete assignments and projects.  
* Instructor is introducing GitHub with students this year


## Course Overview ##

This course is equivalent to a rigorous, non-calculus based, college introductory statistics course. Students will learn standard distribution-based inference procedures, including 
[Overview from College Board](http://media.collegeboard.com/digitalServices/pdf/ap/ap-course-overviews/ap-statistics-course-overview.pdf)

## Learning ##

"Learning is creation, not consumption. Knowledge is not something a learner absorbs, but something a learner creates. Learning happens when a learner integrates new knowledge and skill into his or her existing structure of self. Learning is literally a matter of creating new meanings, new neural networks, and new patterns of electro/chemical interactions within one's total brain/body system."
[~ The Center for Accelerated Learning](http://www.alcenter.com/what_is.php)

## Rules for Me as Your Instructor ##
1. Set and enforce high expectations. 
2. Provide the tools to achieve them. 
3. Respect your humanity.    
  
Adapted from a 14JUL2017 Tweet by Lara Schwartz, "I teach law and government at American University. My dog thinks I'm smart."

## Homework and other assignments ##

* Homework and other assignments are regular opportunities for you to create learning. All assignments will be posted on Canvas and listed on the due date for consistency throughout the year. ALL ASSIGNMENTS ARE DUE AT THE START OF CLASS ON THE DUE DATE, UNLESS OTHERWISE NOTED.
   * Textbook homework assignments may be done as traditional math homework on notebook paper or in a spiral notebook (student's choice for how to organize). 
  * Canvas assignments that are to be handed in electronically on Canvas will have the submit button available. When appropriate, students will usually be given options such as editing a text box, attaching a document, providing link to GoogleDoc, or attaching an audio or video file. 
  * Programming assignments that are submitted on GitHub will use the following workflow:
    * Fork the repository for the exercise/project (found under github.com/APStats).
    * Clone the repository to your computer.
    * Open the index.html file in a browser and open the Developer Tools.
    * Modify the files to complete your solution.
    * Refresh the index.html page to see results and repeat.
    * Make sure all of your code is committed.
    * Push/sync up to GitHub.
    * Create a pull request on the original repository.
    * You may continue to push fixes and improvements until the due date - just add a comment in the pull request to let me know it has been updated.
    * 

### Extra Credit ###

Bonus points for:
* Creativity
* Anything listed under BONUS in the README of the exercise.
* 


## Resources

### Required Reading

* [Google JavaScript Style Guide](http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml)
* [JavaScript Garden](http://bonsaiden.github.com/JavaScript-Garden/)
* [Mozilla's Introduction to Object-Oriented Javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Introduction_to_Object-Oriented_JavaScript)
* [What’s so great about JavaScript Promises?](http://blog.parse.com/learn/engineering/whats-so-great-about-javascript-promises/)

### Beginner Materials

This class assumes you are confident with this material, but in case you need a brush-up...

* Codecademy – [JavaScript](https://www.codecademy.com/learn/javascript) and [jQuery](https://www.codecademy.com/learn/jquery)
* [Eloquent JavaScript](http://eloquentjavascript.net/index.html) by Marijn Haverbeke, Chapters 1-5
* [Want to learn JavaScript in 2015?](https://medium.com/@_cmdv_/i-want-to-learn-javascript-in-2015-e96cd85ad225)
* [How jQuery Works](https://learn.jquery.com/about-jquery/how-jquery-works/)
* see also – [Other Lists](#other-lists)

### Recommended Reading

* [Functional JavaScript](http://shop.oreilly.com/product/0636920028857.do) by Michael Fogus
* [Front-end Job Interview Questions](https://github.com/h5bp/Front-end-Developer-Interview-Questions) by @darcyclarke (for testing yourself)
* [JavaScript Best Practices](http://www.thinkful.com/learn/javascript-best-practices-1/)
* [JavaScript Patterns](http://shichuan.github.io/javascript-patterns/) by @shichuan (thanks @iandrewfuchs)
* [JavaScript Patterns](http://www.amazon.com/JavaScript-Patterns-Stoyan-Stefanov/dp/0596806752) by Stoyan Stephanov
* [JavaScript Web Applications](http://www.amazon.com/JavaScript-Web-Applications-Alex-MacCaw/dp/144930351X/) by Alex MacCaw
* [JavaScript: The Good Parts](http://www.amazon.com/JavaScript-Good-Parts-Douglas-Crockford/dp/0596517742) by Douglas Crockford
* [Learning Advanced JavaScript slides](http://ejohn.org/apps/learn/) by John Resig
* [Static Web Apps](http://www.staticapps.org/)
* [Test-Driven JavaScript Development](http://www.amazon.com/Test-Driven-JavaScript-Development-Developers-Library/dp/0321683919) by Christian Johansen
* [The JavaScript Interpreter, Interpreted](http://www.slideshare.net/marthakelly/js-interpreter-interpreted) by Martha Girdler [(video)](https://www.youtube.com/watch?v=iSxNCYcPAFk)
* 
#### Specific Topics

* [Classical Inheritance in JavaScript](http://www.crockford.com/javascript/inheritance.html) by Douglas Crockford
* [Partial Application in JavaScript](http://benalman.com/news/2012/09/partial-application-in-javascript/) by Ben Alman (thanks @michaelBenin)
* [HTML5 Rocks](http://www.html5rocks.com)
* [Learning JavaScript Design Patterns](http://addyosmani.com/resources/essentialjsdesignpatterns/book/) by Addy Osmani

#### Other Lists

* [JS: The Right Way](http://www.jstherightway.org/) (an overview of the JS landscape)
* [Code School](https://www.codeschool.com/paths/javascript)
* Thoughtbot's [Javascript Trail Map](https://upcase.com/javascript)
* [How To Learn JavaScript Properly](http://javascriptissexy.com/how-to-learn-javascript-properly/)
* [Superhero.js](http://superherojs.com)
* [Teach Yourself to Code](http://teachyourselftocode.com/javascript)

### Tools

* code validation: [JSLint](http://jslint.com) / [JSHint](http://jshint.com)
* debugging:
    * [Chrome Developer Tools](https://developer.chrome.com/devtools/index)
        * [Official debugging tutorial](https://developer.chrome.com/extensions/tut_debugging)
        * Tutorial: [JavaScript Diagnosis](http://www.macwright.org/2015/03/10/javascript-diagnosis.html)
    * [Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/)
* sharing code snippets: [gist.github.com](https://gist.github.com/)
* asking questions: [Stack Overflow](http://stackoverflow.com/)

#### GitHub

* Git and GitHub
    * [Official GitHub Help](https://help.github.com/)
    * [Recommended resources](http://hackerhours.org/resources.html#github)
* GitHub Pages
    * [Official site](https://pages.github.com/)
    * [Thinkful guide](http://www.thinkful.com/learn/a-guide-to-using-github-pages/)

#### HTML/CSS/JS Sandboxes

* [JS Bin](http://jsbin.com/) (recommended)
* [bl.ocks.org](http://bl.ocks.org/)
* [Cloud9](https://c9.io/)
* [CodePen](http://codepen.io/pen/)
* [JSFiddle](http://jsfiddle.net/)
* [Plunker](http://plnkr.co/)
* [rawgithub.com](http://rawgit.com/)

#### Frameworks

* Framework comparison: [TodoMVC](http://todomvc.com)
* [Testing](https://coderwall.com/p/ntbixw)

### Reference

* [Mozilla Developer Network](https://developer.mozilla.org/en/JavaScript) and [Learn JavaScript](https://developer.mozilla.org/en-US/learn/javascript)
* [w3schools](http://www.w3schools.com/jsref/default.asp)
* [JavaScript: The Definitive Guide](http://shop.oreilly.com/product/9780596000486.do) by David Flanagan
* [Simplified JavaScript Jargon](http://jargon.js.org/)

### More Examples

* [map/reduce](http://jsbin.com/ojapAsUR/2/edit?js) (in [Underscore](http://underscorejs.org/#map))

## Grading

* Tests – 70%
* Homework – 15%
* Journal – 15%

## Exam ##
* 
* AP: Students are required to take the AP exam in May in order to earn AP credit for this course. Failure to take the AP exam will result in the FINAL grade for the course being reduced by one letter grade (minimum of 10 points).
* 
* Teacher-made final
* * A practice AP exam will be given in April and will count for at least 70% of the teacher-made final exam grade.
*  
* Exam Exemption: Students are eligible in this course for exam exemptions per the WSFCS Exam Exemption policy. The exemption is for the teacher-made exam given at the end of this course.


## Academic Integrity ##
* 
* WARNING: Cheating on exams can be STATISTICALLY UNCOVERED. DON’T TRY IT! Don’t throw your future away.
* 
## Attendance ##
* 
* Students are expected to attend all of their CC classes each day. When a student has to be absent, they should bring a parent note or an official note if applicable (doctor, dentist, court) for that absence within 2 days of their return to CC. Students who do not submit an acceptable note within 2 days will have their absence coded as UNEXCUSED. A student with more than 3 UNEXCUSED absences in a SEMESTER has violated the CC attendance policy and may receive an “FF” for semester average in each course where they violated the policy.
* 

### Instructor

* Kay Endriss, MS, NBCT
